### ISSUE TITLE
Add override for/expose mod info during/after option creation

### ISSUE THREAD

**Issue by ThinkInvis** [Rune580/RiskOfOptions#18]
I recently added support for Risk Of Options to TILER2's AutoConfig module (ThinkInvis/TILER2@dbdb9922e925c580d0bfe1c10471986dae199464 and ThinkInvis/TILER2@a1d58c36a6632c7018a095d21bf8647350fa96c2), but discovered that this causes options to be incorrectly registered under TILER2's mod name instead of the name of the mod using AutoConfig. AutoConfig also uses `Assembly.GetCallingAssembly()` to prepare a mod name for its internal BepInEx config entries, so all I need is a way to pass that information through to ROO in place of its own uses of `GetCallingAssembly`.

**Comment by ThinkInvis** [comment]
Correction: AutoConfig takes a mod name as a string; another system (T2Module) that implements AutoConfigContainer is what uses `GetCallingAssembly`.

**Comment by Rune580** [comment]
should be simple to provide an override for the modinfo

**Comment by Rune580** [comment]
Overrides have been added c360c6f4ff26585eb718354755733f018c87786e. An update should be out soon.

**Comment by Rune580** [comment]
Update has been pushed out.
