### ISSUE TITLE
Missing option type(s) for int configs

### ISSUE THREAD

**Issue by ThinkInvis** [Rune580/RiskOfOptions#19]
None of the existing options seem to support int as an underlying data type. Casting from a float config for purposes where an int is suitable could lead to precision issues. An IntSlider option type or similar would be nice -- maybe a range AKA numeric up/down control (would also work well for wider/unspecified limits on float configs)?

**Comment by Rune580** [comment]
I thought for sure I made an option for that, but you're 100% right, nothing directly supports an int. Shouldn't be too hard to add though.

**Comment by Rune580** [comment]
As of c5a7a52d4f9108dbbf231bd55d59bf4c4a846a96 there is now an IntSliderOption, update will be out very shortly.
