### ISSUE TITLE
Category tab breadcrumbs cover entire vertical space of categories panel

### ISSUE THREAD

**Issue by ThinkInvis** [Rune580/RiskOfOptions#20]
If there are enough categories to require multiple pages (5+?), the diamond icons that appear below categories to indicate pagination will cover the entire vertical space of the categories panel. Despite not visually overlapping the category buttons, they will still intercept attempts to click any category buttons directly above them, causing a page scroll instead of the desired category switch.

**Comment by Rune580** [comment]
unfortunately for me this isn't the first time this bug has come up. It reared its ugly head 3 times before I released 2.0, I thought for sure I crushed it then.

**Comment by Rune580** [comment]
Fixed by 045473e531b3adbeb3f88c741e1d61e9b03f7a28, update has been pushed.
