### ISSUE TITLE
Input field Controller causes massive hitches if you use multiple string input fields

### ISSUE THREAD

**Issue by Bubbet** [Rune580/RiskOfOptions#22]
Hooking and unhooking language.getstring for each input field is causing huge hitches when opening the category. 

Came across this issue because i'm using it for color values as html strings because there is no controller for colors.

**Comment by Rune580** [comment]
Input fields are next on the list to clean up. I'll also look into adding a color wheel option.

**Comment by Rune580** [comment]
Fixed, I'll close this when the update is out. Keep an eye out on #23 as I'm now working on getting that out for this update.
