### ISSUE TITLE
nothing spawns

### ISSUE THREAD

**Issue by cl0udz2026** [Rune580/RiskOfOptions#29]
there is a HUGE problem with something were nothing will spawn. I deleted risk of options and the game worked fine. plz fix soon if u need me to list all mods i have to try for yourself i can do that for u.

**Comment by Rune580** [comment]
If you're using R2ModMan, could you send me the pack code. Otherwise please provide a list of the mods. And if you could, a log from when this issue happens would help.

**Comment by cl0udz2026** [comment]
here are all the mods that i have 
bepinex 
mmhook
better ui
risk of options 
stage aesthetic 
lost thru time skin pack

**Comment by Rune580** [comment]
I need more info before I can look into it. Are you using r2modman?

**Comment by cl0udz2026** [comment]
noim not should i?

**Comment by Rune580** [comment]
If you're not then don't worry about it. Can you provide the log file for when this issue happens.

**Comment by cl0udz2026** [comment]
how would i get that?

**Comment by Rune580** [comment]
![image](https://user-images.githubusercontent.com/12521934/201547401-7d5316bb-2376-454b-8a7d-c9556ba3b3c4.png)

**Comment by Rune580** [comment]
make sure to grab it after you experience the issue, because the log clears itself after you launch the game

**Comment by cl0udz2026** [comment]
okay gimmie a sec

**Comment by cl0udz2026** [comment]
it might take a while because it doesn't happen all the time

**Comment by cl0udz2026** [comment]
[Message:   BepInEx] BepInEx 5.4.21.0 - Risk of Rain 2 (8/29/2022 8:22:58 PM)
[Info   :   BepInEx] Running under Unity v2019.4.26.14694700
[Info   :   BepInEx] CLR runtime version: 4.0.30319.17020
[Info   :   BepInEx] Supports SRE: False
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.21.0]
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.MonoMod.HookGenPatcher 1.2.1.0]
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.GUI.Patcher 1.0.0.0]
[Info   :   BepInEx] Loaded 1 patcher method from [FixPluginTypesSerialization 1.0.0.0]
[Info   :   BepInEx] 4 patcher plugins loaded
[Info   :BepInEx.GUI] Finding and launching GUI
[Info   :BepInEx.GUI] Found GUI Executable in C:\Program Files (x86)\Steam\steamapps\common\Risk of Rain 2\BepInEx\patchers\BepInExGUI\rust\windows_x64\bepinex_gui.exe
[Info   :BepInEx.GUI] [SendLogToClient] Accepting Socket.
[Info   :HookGenPatcher] Previous MMHOOK location found. Using that location to save instead.
[Info   :HookGenPatcher] Already ran for this version, reusing that file.
[Message:FixPluginTypesSerialization] Using the config cache
[Info   :FixPluginTypesSerialization] Running under Unity v2019.4.26
[Debug  :FixPluginTypesSerialization] Unity version obtained from main application module.
[Info   :   BepInEx] Patching [RoR2] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 7 plugins to load
[Info   :   BepInEx] Loading [RoR2BepInExPack 1.2.0]
[Info   :   BepInEx] Loading [LostThroughTime 1.0.7]
[Info   :   BepInEx] Loading [PlagueBandit 1.0.0]
[Error  :BepInEx.GUI] Error while trying to send log to socket: System.Net.Sockets.SocketException (0x80004005): Connection reset by peer
  at System.Net.Sockets.Socket.Send (System.Byte[] buffer, System.Int32 offset, System.Int32 size, System.Net.Sockets.SocketFlags socketFlags) [0x00016] in <6b80e2850f1c48e6a227f0818ca6b227>:IL_0016 
  at System.Net.Sockets.Socket.Send (System.Byte[] buffer) [0x00000] in <6b80e2850f1c48e6a227f0818ca6b227>:IL_0000 
  at BepInEx.GUI.SendLogToClientSocket.SendPacketsToClientUntilConnectionIsClosed (System.Net.Sockets.Socket clientSocket) [0x0001c] in <c08c94904db949e8a7b70c185edb39a5>:IL_001C 
Disconnecting socket.
[Info   :BepInEx.GUI] [SendLogToClient] Accepting Socket.
[Info   :   BepInEx] Loading [Risk Of Options 2.5.3]
[Info   :   BepInEx] Loading [StageAesthetic 0.7.3]
[Error  : Unity Log] FileNotFoundException: Could not load file or assembly 'R2API, Version=4.3.5.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Stack trace:
System.MonoCustomAttrs.GetCustomAttributesBase (System.Reflection.ICustomAttributeProvider obj, System.Type attributeType, System.Boolean inheritedOnly) (at <44afb4564e9347cf99a1865351ea8f4a>:IL_0013)
System.MonoCustomAttrs.GetCustomAttributes (System.Reflection.ICustomAttributeProvider obj, System.Type attributeType, System.Boolean inherit) (at <44afb4564e9347cf99a1865351ea8f4a>:IL_0037)
System.RuntimeType.GetCustomAttributes (System.Type attributeType, System.Boolean inherit) (at <44afb4564e9347cf99a1865351ea8f4a>:IL_0038)
BepInEx.MetadataHelper.GetMetadata (System.Type pluginType) (at <57549b86c0f64bb79f4b6542479e6770>:IL_0000)
BepInEx.MetadataHelper.GetMetadata (System.Object plugin) (at <57549b86c0f64bb79f4b6542479e6770>:IL_0006)
BepInEx.BaseUnityPlugin..ctor () (at <57549b86c0f64bb79f4b6542479e6770>:IL_0006)
StageAesthetic.Main..ctor () (at <d6cc8dcbbf6f4fd3bb28ac1253ae6d64>:IL_0000)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
FlashWindow:.cctor()

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
StageAesthetic.SwapVariants.Initialize () (at <d6cc8dcbbf6f4fd3bb28ac1253ae6d64>:IL_0076)
StageAesthetic.Main.Awake () (at <d6cc8dcbbf6f4fd3bb28ac1253ae6d64>:IL_002E)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
FlashWindow:.cctor()

[Info   :   BepInEx] Loading [DinoMul-T 1.0.3]
[Info   :   BepInEx] Loading [BetterUI 2.6.4]
[Message:   BepInEx] Chainloader startup complete
[Warning: Unity Log] Network message MsgType.Highest + 22 is unregistered.
[Info   : Unity Log] buildId = 1.2.4.1
[Info   : Unity Log] WwiseUnity: Wwise(R) SDK Version 2019.2.12 Build 7544.
[Info   : Unity Log] WwiseUnity: Setting Plugin DLL path to: C:/Program Files (x86)/Steam/steamapps/common/Risk of Rain 2/Risk of Rain 2_Data\Plugins\x86_64
[Info   : Unity Log] WwiseUnity: Sound engine initialized successfully.
[Info   : Unity Log] Active scene changed from  to loadingbasic
[Error  : Unity Log] FileNotFoundException: Could not load file or assembly 'R2API, Version=4.3.5.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Stack trace:
UnityEngine.SceneManagement.SceneManager.Internal_SceneLoaded (UnityEngine.SceneManagement.Scene scene, UnityEngine.SceneManagement.LoadSceneMode mode) (at <469e86e97fa2467ebffe49bbd6086325>:IL_000E)

[Info   : Unity Log] application data path isC:/Program Files (x86)/Steam/steamapps/common/Risk of Rain 2/Risk of Rain 2_Data
[Info   :   Console] Facepunch.Steamworks Unity: WindowsPlayer
[Info   :   Console] Facepunch.Steamworks Os: Windows
[Info   :   Console] Facepunch.Steamworks Arch: x64
[Info   : Unity Log] PlatformSystems:InitNetworkManagerSystem
[Info   : Unity Log] Launch Parameters: 
  arg[0]="C:\Program Files (x86)\Steam\steamapps\common\Risk of Rain 2\Risk of Rain 2.exe"

[Info   : Unity Log] "usesocialiconflag" is not a recognized ConCommand or ConVar.
[Info   : Unity Log] Loaded archived convars.
[Info   : Unity Log] Could not load config /Config/autoexec.cfg: Could not find file "C:\Program Files (x86)\Steam\steamapps\common\Risk of Rain 2\Risk of Rain 2_Data\Config\autoexec.cfg"
[Info   : Unity Log] LoadContentPacks() start
[Warning: Unity Log] Failed to assign Buffs.Deafened: Asset "bdDeafened" not found.
[Warning: Unity Log] Failed to assign Items.SummonedEcho: Asset "SummonedEcho" not found.
[Warning: Unity Log] Failed to assign Equipment.AffixEcho: Asset "EliteEchoEquipment" not found.
[Warning: Unity Log] Failed to assign Buffs.AffixEcho: Asset "bdEliteEcho" not found.
[Warning: Unity Log] Failed to assign Elites.Echo: Asset "edEcho" not found.
[Info   : Unity Log] LoadContentPacks() end
[Warning: Unity Log] Could not find scene with name "loadingbasic".
[Warning: Unity Log] Could not find scene with name "intro".
[Info   : Unity Log] Command "set_scene" failed: "intro" is not a valid scene.
[Info   : Unity Log] Game content load completed in 12542ms.
[Info   : Unity Log] Setting current language to "en"
[Error  : Unity Log] [RoR2.ItemCatalog] Unable to register BuffInfo for Deafened
[Info   : Unity Log] [RoR2.Stats.StatSheet] init stat sheet
[Info   : Unity Log] Attempting to load user profile /UserProfiles/fbf6c11c-3911-4f0d-b143-072764e4c507.xml
[Info   : Unity Log] stream.Length=231305
[Info   : Unity Log] Tried to add duplicate node /Logbook/LOGBOOK_CATEGORY_MONSTER/NULLIFIER_BODY_NAME
[Info   : Unity Log] Tried to add duplicate node /Logbook/LOGBOOK_CATEGORY_MONSTER/VOIDJAILER_BODY_NAME
[Info   : Unity Log] Tried to add duplicate node /Logbook/LOGBOOK_CATEGORY_MONSTER/VOIDMEGACRAB_BODY_NAME
[Info   : Unity Log] Unloaded scene loadingbasic
[Info   : Unity Log] Active scene changed from  to splash
[Error  : Unity Log] FileNotFoundException: Could not load file or assembly 'R2API, Version=4.3.5.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Stack trace:
UnityEngine.SceneManagement.SceneManager.Internal_SceneLoaded (UnityEngine.SceneManagement.Scene scene, UnityEngine.SceneManagement.LoadSceneMode mode) (at <469e86e97fa2467ebffe49bbd6086325>:IL_000E)

[Info   : Unity Log] Setting offline scene to intro
[Info   : Unity Log] Unloaded scene splash
[Info   : Unity Log] Active scene changed from  to intro
[Error  : Unity Log] FileNotFoundException: Could not load file or assembly 'R2API, Version=4.3.5.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Stack trace:
UnityEngine.SceneManagement.SceneManager.Internal_SceneLoaded (UnityEngine.SceneManagement.Scene scene, UnityEngine.SceneManagement.LoadSceneMode mode) (at <469e86e97fa2467ebffe49bbd6086325>:IL_000E)

[Info   : Unity Log] Setting offline scene to title
[Info   : Unity Log] Unloaded scene intro
[Info   : Unity Log] Active scene changed from  to title
[Error  : Unity Log] FileNotFoundException: Could not load file or assembly 'R2API, Version=4.3.5.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Stack trace:
UnityEngine.SceneManagement.SceneManager.Internal_SceneLoaded (UnityEngine.SceneManagement.Scene scene, UnityEngine.SceneManagement.LoadSceneMode mode) (at <469e86e97fa2467ebffe49bbd6086325>:IL_000E)

[Info   : Unity Log] BaseMainMenuScreen: OnEnter()
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object.
Stack trace:
RoR2.UI.SkinControllers.ButtonSkinController.StaticUpdate () (at <abee4f3b46184662b4d0bd0bc9965114>:IL_0014)
RoR2.RoR2Application.Update () (at <abee4f3b46184662b4d0bd0bc9965114>:IL_005F)

[Info   : Unity Log] NetworkManagerSystem.desiredHost={ hostType=Self listen=False maxPlayers=4 }
[Warning: Unity Log] The prefab 'ArenaMissionController' has multiple NetworkIdentity components. There can only be one NetworkIdentity on a prefab, and it must be on the root object.
[Warning: Unity Log] The prefab 'Moon2DropshipZone' has multiple NetworkIdentity components. There can only be one NetworkIdentity on a prefab, and it must be on the root object.
[Warning: Unity Log] The prefab 'HOLDER_ Gauntlets' has multiple NetworkIdentity components. There can only be one NetworkIdentity on a prefab, and it must be on the root object.
[Warning: Unity Log] The prefab 'VoidCamp' has multiple NetworkIdentity components. There can only be one NetworkIdentity on a prefab, and it must be on the root object.
[Info   : Unity Log] Unloaded scene title
[Info   : Unity Log] Active scene changed from  to lobby
[Error  : Unity Log] FileNotFoundException: Could not load file or assembly 'R2API, Version=4.3.5.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Stack trace:
UnityEngine.SceneManagement.SceneManager.Internal_SceneLoaded (UnityEngine.SceneManagement.Scene scene, UnityEngine.SceneManagement.LoadSceneMode mode) (at <469e86e97fa2467ebffe49bbd6086325>:IL_000E)

[Info   : Unity Log] Adding local player controller 0 on connection hostId: -1 connectionId: 0 isReady: False channel count: 0
[Info   : Unity Log] NetworkManagerSystem.AddPlayerInternal(conn=hostId: -1 connectionId: 0 isReady: False channel count: 0, playerControllerId=0, extraMessageReader=NetBuf sz:259 pos:259
[Info   : Unity Log] OnClientSceneChanged networkSceneName=lobby loadedScenes=lobby
[Error  : Unity Log] A connection has already been set as ready. There can only be one.
[Info   : Unity Log] Player 0 already added, aborting.
[Info   : Unity Log] SetSurvivorPreferenceClient survivorIndex=8, bodyIndex=75
[Info   : Unity Log] Changinging body preference for cl0udz (RoR2.NetworkUserId) from None to 75
[Info   : Unity Log] Changinging body preference for cl0udz (RoR2.NetworkUserId) from None to 75
[Info   : Unity Log] Could not load config /Config/server_pregame.cfg: Could not find file "C:\Program Files (x86)\Steam\steamapps\common\Risk of Rain 2\Risk of Rain 2_Data\Config\server_pregame.cfg"
[Info   : Unity Log] Attempting to generate PreGameVoteController for cl0udz
[Info   : Unity Log] PreGameRuleVoteController.ClientTransmitVotesToServer()
[Info   : Unity Log] Received vote from cl0udz
[Info   : Unity Log] Accepting vote from cl0udz
[Info   : Unity Log] <style=cEvent>cl0udz connected.</color>
[Info   : Unity Log] NetworkUser(Clone) (RoR2.NetworkUser)
[Info   : Unity Log] maxRuleCount=11, currentChoiceIndex=0
[Info   : Unity Log] SetSurvivorPreferenceClient survivorIndex=7, bodyIndex=70
[Info   : Unity Log] Changinging body preference for cl0udz (RoR2.NetworkUserId) from 75 to 70
[Info   : Unity Log] Changinging body preference for cl0udz (RoR2.NetworkUserId) from 75 to 70
[Info   : Unity Log] SetSurvivorPreferenceClient survivorIndex=9, bodyIndex=80
[Info   : Unity Log] Changinging body preference for cl0udz (RoR2.NetworkUserId) from 70 to 80
[Info   : Unity Log] Changinging body preference for cl0udz (RoR2.NetworkUserId) from 70 to 80
[Info   : Unity Log] Run seed:  17114575819705154107
[Info   : Unity Log] PickupDropTable 'dtDoppelganger' has been loaded after the Run started.  This might be an issue with asset duplication across bundles, or it might be fine.  Regenerating...
[Info   : Unity Log] Unloaded scene lobby
[Info   : Unity Log] Active scene changed from  to golemplains2
[Error  : Unity Log] FileNotFoundException: Could not load file or assembly 'R2API, Version=4.3.5.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Stack trace:
UnityEngine.SceneManagement.SceneManager.Internal_SceneLoaded (UnityEngine.SceneManagement.Scene scene, UnityEngine.SceneManagement.LoadSceneMode mode) (at <469e86e97fa2467ebffe49bbd6086325>:IL_000E)
UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle`1:WaitForCompletion()
RoR2.LegacyResourcesAPI:Load(String)
RoR2.Artifacts.DoppelgangerInvasionManager:Start()

[Info   : Unity Log] OnClientSceneChanged networkSceneName=golemplains2 loadedScenes=golemplains2
[Info   : Unity Log] Client ready.
[Info   : Unity Log] Player 0 already added, aborting.
[Info   : Unity Log] Spending 220 credits on interactables...
[Info   : Unity Log] reorder list
[Error  : Unity Log] Object PodGroundImpact(Clone) (UnityEngine.GameObject) should not be instantiated by means other than EffectManager.SpawnEffect. This WILL result in an NRE!!! Use EffectManager.SpawnEffect or don't use EffectComponent!!!!!
[Info   : Unity Log] NetworkManagerSystem.desiredHost={ hostType=None }
[Info   : Unity Log] Network shutting down...
[Info   : Unity Log] Server shutting down...
[Info   : Unity Log] Issued kick message to all remote clients.
[Info   : Unity Log] Finished waiting for clients to disconnect.
[Info   : Unity Log] StopHost()
[Info   : Unity Log] Server shutdown complete.
[Info   : Unity Log] Unloaded scene golemplains2
[Info   : Unity Log] Active scene changed from  to title
[Error  : Unity Log] FileNotFoundException: Could not load file or assembly 'R2API, Version=4.3.5.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Stack trace:
UnityEngine.SceneManagement.SceneManager.Internal_SceneLoaded (UnityEngine.SceneManagement.Scene scene, UnityEngine.SceneManagement.LoadSceneMode mode) (at <469e86e97fa2467ebffe49bbd6086325>:IL_000E)

[Info   : Unity Log] BaseMainMenuScreen: OnEnter()
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object.
Stack trace:
RoR2.UI.SkinControllers.ButtonSkinController.StaticUpdate () (at <abee4f3b46184662b4d0bd0bc9965114>:IL_0014)
RoR2.RoR2Application.Update () (at <abee4f3b46184662b4d0bd0bc9965114>:IL_005F)

[Info   : Unity Log] NetworkManagerSystem.desiredHost={ hostType=Self listen=False maxPlayers=4 }
[Warning: Unity Log] The prefab 'ArenaMissionController' has multiple NetworkIdentity components. There can only be one NetworkIdentity on a prefab, and it must be on the root object.
[Warning: Unity Log] The prefab 'Moon2DropshipZone' has multiple NetworkIdentity components. There can only be one NetworkIdentity on a prefab, and it must be on the root object.
[Warning: Unity Log] The prefab 'HOLDER_ Gauntlets' has multiple NetworkIdentity components. There can only be one NetworkIdentity on a prefab, and it must be on the root object.
[Warning: Unity Log] The prefab 'VoidCamp' has multiple NetworkIdentity components. There can only be one NetworkIdentity on a prefab, and it must be on the root object.
[Info   : Unity Log] Unloaded scene title
[Info   : Unity Log] Active scene changed from  to lobby
[Error  : Unity Log] FileNotFoundException: Could not load file or assembly 'R2API, Version=4.3.5.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Stack trace:
UnityEngine.SceneManagement.SceneManager.Internal_SceneLoaded (UnityEngine.SceneManagement.Scene scene, UnityEngine.SceneManagement.LoadSceneMode mode) (at <469e86e97fa2467ebffe49bbd6086325>:IL_000E)

[Info   : Unity Log] Adding local player controller 0 on connection hostId: -1 connectionId: 0 isReady: False channel count: 0
[Info   : Unity Log] NetworkManagerSystem.AddPlayerInternal(conn=hostId: -1 connectionId: 0 isReady: False channel count: 0, playerControllerId=0, extraMessageReader=NetBuf sz:259 pos:259
[Info   : Unity Log] OnClientSceneChanged networkSceneName=lobby loadedScenes=lobby
[Error  : Unity Log] A connection has already been set as ready. There can only be one.
[Info   : Unity Log] Player 0 already added, aborting.
[Info   : Unity Log] SetSurvivorPreferenceClient survivorIndex=9, bodyIndex=80
[Info   : Unity Log] Changinging body preference for cl0udz (RoR2.NetworkUserId) from None to 80
[Info   : Unity Log] Changinging body preference for cl0udz (RoR2.NetworkUserId) from None to 80
[Info   : Unity Log] Could not load config /Config/server_pregame.cfg: Could not find file "C:\Program Files (x86)\Steam\steamapps\common\Risk of Rain 2\Risk of Rain 2_Data\Config\server_pregame.cfg"
[Info   : Unity Log] Attempting to generate PreGameVoteController for cl0udz
[Info   : Unity Log] Applying persistent ballot of votes for LocalUser cl0udz.
[Info   : Unity Log] PreGameRuleVoteController.ClientTransmitVotesToServer()
[Info   : Unity Log] Received vote from cl0udz
[Info   : Unity Log] Accepting vote from cl0udz
[Info   : Unity Log] <style=cEvent>cl0udz connected.</color>
[Info   : Unity Log] Run seed:  2837386572142454348
[Info   : Unity Log] Unloaded scene lobby
[Warning: Unity Log] Couldn't create a Convex Mesh from source mesh "Rock Formations 5" within the maximum polygons limit (256). The partial hull will be used. Consider simplifying your mesh.
[Info   : Unity Log] Active scene changed from  to snowyforest
[Error  : Unity Log] FileNotFoundException: Could not load file or assembly 'R2API, Version=4.3.5.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Stack trace:
UnityEngine.SceneManagement.SceneManager.Internal_SceneLoaded (UnityEngine.SceneManagement.Scene scene, UnityEngine.SceneManagement.LoadSceneMode mode) (at <469e86e97fa2467ebffe49bbd6086325>:IL_000E)

[Info   : Unity Log] OnClientSceneChanged networkSceneName=snowyforest loadedScenes=snowyforest
[Info   : Unity Log] Client ready.
[Info   : Unity Log] Player 0 already added, aborting.
[Info   : Unity Log] Spending 300 credits on interactables...
[Info   : Unity Log] reorder list
[Info   : Unity Log] <style=cWorldEvent>A blue orb appears..</style>
[Error  : Unity Log] Object PodGroundImpact(Clone) (UnityEngine.GameObject) should not be instantiated by means other than EffectManager.SpawnEffect. This WILL result in an NRE!!! Use EffectManager.SpawnEffect or don't use EffectComponent!!!!!
[Info   : Unity Log] NetworkManagerSystem.desiredHost={ hostType=None }
[Info   : Unity Log] Network shutting down...
[Info   : Unity Log] Server shutting down...
[Info   : Unity Log] Issued kick message to all remote clients.
[Info   : Unity Log] Finished waiting for clients to disconnect.
[Info   : Unity Log] StopHost()
[Info   : Unity Log] Server shutdown complete.
[Info   : Unity Log] Unloaded scene snowyforest
[Info   : Unity Log] Active scene changed from  to title
[Error  : Unity Log] FileNotFoundException: Could not load file or assembly 'R2API, Version=4.3.5.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Stack trace:
UnityEngine.SceneManagement.SceneManager.Internal_SceneLoaded (UnityEngine.SceneManagement.Scene scene, UnityEngine.SceneManagement.LoadSceneMode mode) (at <469e86e97fa2467ebffe49bbd6086325>:IL_000E)

[Info   : Unity Log] BaseMainMenuScreen: OnEnter()
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object.
Stack trace:
RoR2.UI.SkinControllers.ButtonSkinController.StaticUpdate () (at <abee4f3b46184662b4d0bd0bc9965114>:IL_0014)
RoR2.RoR2Application.Update () (at <abee4f3b46184662b4d0bd0bc9965114>:IL_005F)

[Info   : Unity Log] NetworkManagerSystem.desiredHost={ hostType=Self listen=False maxPlayers=4 }
[Warning: Unity Log] The prefab 'ArenaMissionController' has multiple NetworkIdentity components. There can only be one NetworkIdentity on a prefab, and it must be on the root object.
[Warning: Unity Log] The prefab 'Moon2DropshipZone' has multiple NetworkIdentity components. There can only be one NetworkIdentity on a prefab, and it must be on the root object.
[Warning: Unity Log] The prefab 'HOLDER_ Gauntlets' has multiple NetworkIdentity components. There can only be one NetworkIdentity on a prefab, and it must be on the root object.
[Warning: Unity Log] The prefab 'VoidCamp' has multiple NetworkIdentity components. There can only be one NetworkIdentity on a prefab, and it must be on the root object.
[Info   : Unity Log] Unloaded scene title
[Info   : Unity Log] Active scene changed from  to lobby
[Error  : Unity Log] FileNotFoundException: Could not load file or assembly 'R2API, Version=4.3.5.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Stack trace:
UnityEngine.SceneManagement.SceneManager.Internal_SceneLoaded (UnityEngine.SceneManagement.Scene scene, UnityEngine.SceneManagement.LoadSceneMode mode) (at <469e86e97fa2467ebffe49bbd6086325>:IL_000E)

[Info   : Unity Log] Adding local player controller 0 on connection hostId: -1 connectionId: 0 isReady: False channel count: 0
[Info   : Unity Log] NetworkManagerSystem.AddPlayerInternal(conn=hostId: -1 connectionId: 0 isReady: False channel count: 0, playerControllerId=0, extraMessageReader=NetBuf sz:259 pos:259
[Info   : Unity Log] OnClientSceneChanged networkSceneName=lobby loadedScenes=lobby
[Error  : Unity Log] A connection has already been set as ready. There can only be one.
[Info   : Unity Log] Player 0 already added, aborting.
[Info   : Unity Log] SetSurvivorPreferenceClient survivorIndex=9, bodyIndex=80
[Info   : Unity Log] Changinging body preference for cl0udz (RoR2.NetworkUserId) from None to 80
[Info   : Unity Log] Changinging body preference for cl0udz (RoR2.NetworkUserId) from None to 80
[Info   : Unity Log] Could not load config /Config/server_pregame.cfg: Could not find file "C:\Program Files (x86)\Steam\steamapps\common\Risk of Rain 2\Risk of Rain 2_Data\Config\server_pregame.cfg"
[Info   : Unity Log] Attempting to generate PreGameVoteController for cl0udz
[Info   : Unity Log] Applying persistent ballot of votes for LocalUser cl0udz.
[Info   : Unity Log] PreGameRuleVoteController.ClientTransmitVotesToServer()
[Info   : Unity Log] Received vote from cl0udz
[Info   : Unity Log] Accepting vote from cl0udz
[Info   : Unity Log] <style=cEvent>cl0udz connected.</color>
[Info   : Unity Log] Run seed:  379793907777028670
[Info   : Unity Log] Unloaded scene lobby
[Warning: Unity Log] Couldn't create a Convex Mesh from source mesh "Rock Formations 5" within the maximum polygons limit (256). The partial hull will be used. Consider simplifying your mesh.
[Info   : Unity Log] Active scene changed from  to snowyforest
[Error  : Unity Log] FileNotFoundException: Could not load file or assembly 'R2API, Version=4.3.5.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Stack trace:
UnityEngine.SceneManagement.SceneManager.Internal_SceneLoaded (UnityEngine.SceneManagement.Scene scene, UnityEngine.SceneManagement.LoadSceneMode mode) (at <469e86e97fa2467ebffe49bbd6086325>:IL_000E)

[Info   : Unity Log] OnClientSceneChanged networkSceneName=snowyforest loadedScenes=snowyforest
[Info   : Unity Log] Client ready.
[Info   : Unity Log] Player 0 already added, aborting.
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
StageAesthetic.SwapVariants.ChangeProfile (System.String scenename) (at <d6cc8dcbbf6f4fd3bb28ac1253ae6d64>:IL_094D)
StageAesthetic.SwapVariants.SceneDirector_Start (On.RoR2.SceneDirector+orig_Start orig, RoR2.SceneDirector self) (at <d6cc8dcbbf6f4fd3bb28ac1253ae6d64>:IL_000D)
DMD<>?-283035648.Hook<RoR2.SceneDirector::Start>?1509093376 (RoR2.SceneDirector ) (at <c04c1d6ebba845e2ba6e1b29bc5b1cfa>:IL_000A)

[Error  : Unity Log] Object PodGroundImpact(Clone) (UnityEngine.GameObject) should not be instantiated by means other than EffectManager.SpawnEffect. This WILL result in an NRE!!! Use EffectManager.SpawnEffect or don't use EffectComponent!!!!!

**Comment by Rune580** [comment]
Do you have R2API installed?

**Comment by cl0udz2026** [comment]
would it be in plugins?
because if so when i regot all my mods i prob forgot it

**Comment by Rune580** [comment]
In the future you should be using r2modman, as it will automatically handle any needed dependencies. StageAsthetic requires both R2API and RoO as dependencies. Without R2API it fails when the game is trying to load a stage which causes nothing to spawn, without RoO the mod doesn't even hook into the game correctly acting as if the mod didn't even load, which is why the game acts as if nothing is wrong. I can see why you thought it was an RoO issue.

**Comment by cl0udz2026** [comment]
thank you. its still odd tho because StageAsthetic still works
