### ISSUE TITLE
Drop down box option

### ISSUE THREAD

**Issue by Rune580** [Rune580/RiskOfOptions#3]
A Drop down box that lets users select an option out of specific choices.

**Comment by Rune580** [comment]
Because of the 2nd rewrite, this is broken.

**Comment by Faustvii** [comment]
Looking forward to seeing this implemented.

**Comment by Rune580** [comment]
Implemented again! will be out in update 2.3.0 which should be out tonight if no major issues come up in testing

**Comment by Rune580** [comment]
Encountered #13 will probably not be releasing 2.3.0 tonight
