### ISSUE TITLE
Add percent option

### ISSUE THREAD

**Issue by Priscillalala** [Rune580/RiskOfOptions#37]
Feature request: RoR2 has a lot of percents (skill damage, stat boosts, % healing, etc.) and they are stored as coefficients, ie 0.5 = 50%. It would be good to have an option to expose a coefficient config value as a percentage to the user. A percent option could also provide the ability to localize the percent sign and placement.

**Comment by Rune580** [comment]
How would you expect this feature to be used in a code example? Because I'm not really understanding how this would look like in the Api.

**Comment by Priscillalala** [comment]
I was thinking either another Option class like this:
```cs
ConfigEntry<float> damageCoefficient = Config.Bind(..., .5f, ...);

ModSettingsManager.AddOption(new PercentOption(damageCoefficient)); // Displays as 50%
```
Or an new option in the FloatFieldConfig and SliderConfig that scales input and output by 100 and formats as a percent
```cs
ConfigEntry<float> damageCoefficient = Config.Bind(..., .5f, ...);

ModSettingsManager.AddOption(new FloatFieldOption(damageCoefficient, new FloatFieldConfig { percent = true })); // Displays as 50%
```
Or just add more ways for modders to customize the options/make new options in general so they can handle things like this

The current format system lets you display the value as a percent but does not let users enter values as a percent, they still have to type .5 instead of 50 for example

**Comment by Rune580** [comment]
> The current format system lets you display the value as a percent but does not let users enter values as a percent, they still have to type .5 instead of 50 for example

wait, I think that might be my fault actually. I'm pretty sure there's a way to use the format string when parsing a float from a string.

**Comment by Rune580** [comment]
looking into it I was wrong, there isn't a built-in way to parse a float from a string using a format string.

**Comment by Rune580** [comment]
Considering adding a field to the slider configs that takes a delegate like `bool Parse(string input, out float? value)`. When the delegate is set in the config, the slider uses it to parse the input string.

**Comment by Rune580** [comment]
To give my idea an example
```csharp
var optionConfig = new SliderConfig
{
    formatString = "{0:0%}",
    TryParseDelegate = (string input, CultureInfo cultureInfo, out float value) => {
        if (!float.TryParse(input, NumberStyles.Any, cultureInfo, out value))
            return false;

        value /= 100f;
        return true;
    }
}
```

Something like this should be flexible enough to handle more use-cases

**Comment by Rune580** [comment]
Could you try the [Artifact from the PR](https://github.com/Rune580/RiskOfOptions/actions/runs/10441673993/artifacts/1824775965) and see if the `TryParseDelegate` provides a suitable solution?
